### ISSUE TITLE
Naming convetions and models

### ISSUE THREAD

**Issue by hayellis** [Oryzone/OryzoneMediaStorageBundle#13]
I'm looking at some things. While the project still is quite small.

All interfaces should (if you adhere to symfony2 standards) be called SomethingInterface, instead of ISomething.
Not to sure with abstract classes tho.

The "entities" folder should probably be renamed to "models", and mapping files for ORM and ODM should be written for easy subclassing.

**Comment by lmammino** [comment]
I have to admit it: i didn't know the subtle difference between entity and model. Just [learned it](http://www.testically.org/2011/05/09/terminology-in-symfony2-and-doctrine2-record-vs-entity-vs-document-vs-model/) and I totally agree with all your suggestions! Thanks!

I'll split the issue into 3 separated issues and mark them for the 1.0 milestone to better organize things to do.
I am stuck on some other high priority projects for the next few days so I will start working on this when i'll have a bit o free time.
Anyway feel free to apply the suggested modifications and submit a pull request if you like, I'll surely merge it.
