### ISSUE TITLE
Write mapping files for ORM and ODM

### ISSUE THREAD

**Issue by lmammino** [Oryzone/OryzoneMediaStorageBundle#17]
Write mapping files for ORM and ODM for easy subclassing (See [FOSUserBundle](https://github.com/FriendsOfSymfony/FOSUserBundle)  as example)

**Comment by hayellis** [comment]
Haha, i wrote some initial mappings. I instinctively used FOSUserBundle as my example :P

**Comment by lmammino** [comment]
Great job @ellis- ! Let me know when you're done! ;)

**Comment by hayellis** [comment]
Theirs a PR with my current code. Ill be updating it as i go before we can merge it.
