### ISSUE TITLE
Integrate useful information into the web developer toolbar (WDT)

### ISSUE THREAD

**Issue by lmammino** [Oryzone/OryzoneMediaStorageBundle#20]
See doctrine bundle code to search examples

E.g.
- https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Doctrine/DataCollector/DoctrineDataCollector.php
- http://symfony.com/doc/current/cookbook/profiler/data_collector.html

**Comment by hayellis** [comment]
https://github.com/doctrine/DoctrineBundle/blob/master/Resources/views/Collector/db.html.twig
