### ISSUE TITLE
ImageProvider throwing ProviderProcessException with incorrect arguments

### ISSUE THREAD

**Issue by piotrminkina** [Oryzone/OryzoneMediaStorageBundle#23]
Missing one argument for thrown ProviderProcessException by ImageProvider.

https://github.com/Oryzone/OryzoneMediaStorageBundle/blob/2.0/Provider/ImageProvider.php#L166 should be

``` php
throw new ProviderProcessException(sprintf('[...]', $media), $this, $media, $variant);
```

instead of

``` php
throw new ProviderProcessException(sprintf('[...]', $media), $media, $variant);
```

**Comment by lmammino** [comment]
Closed with 09fc5a8e531fadfb2163fe030890e82b9df4f583 .
Thanks a lot for reporting it.
Are you using the bundle? This new version is still incomplete and not totally tested, but I'd like to receive a feedback from you if you've tried it.
