### ISSUE TITLE
Symfony 2.2 Support

### ISSUE THREAD

**Issue by mtotheikle** [Oryzone/OryzoneMediaStorageBundle#26]
Has this been tested with 2.2 yet? I noticed the composer file requires 2.1 but wondering if anyone has looked into support for 2.2.

**Comment by lmammino** [comment]
Hello @mtotheikle,
Thanks for being interested in the bundle.

I haven't still tested it with Symfony 2.2. Anyway relying on what I have read on Symfony changelog should not be particular issues with the new version.

Do you have time to test it?
I would love to increment the version in the composer.json if someone can test it and say it's ok with 2.2 ...

**Comment by mtotheikle** [comment]
We are in the process of updating a project, we were going to use 2.1 because of this bundle but I don't think there will be much to update from 2.1 -> 2.2 for this or our own code so I will give it a shot.

**Comment by lmammino** [comment]
Incremented!
Let me know if you'll encounter particular issues! :wink:

**Comment by lmammino** [comment]
I just fixed a BC with form data transformers. I'm closing this issue now. 

@mtotheikle, feel free to reopen it if you notice problems with sf 2.2 (if still using it)

**Comment by mtotheikle** [comment]
@lmammino No problems so far and we have it in production SF2.2 environment; not using all features of it thought so can't be 100% certain.
