### ISSUE TITLE
Difficult to support custom persistance driver

### ISSUE THREAD

**Issue by mtotheikle** [Oryzone/OryzoneMediaStorageBundle#27]
Since OryzoneMediaStorageExtension sets an alias for either doctrine.orm.entity_manager or doctrine.odm.mongodb.document_manager, it is impossible to use a custom driver without defining that definition. The library should take advantage of the EntityManager::getEntityManger factory method like done in the configuration for [FOSOAuthServerBundle orm.xml](https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/blob/master/Resources/config/orm.xml) configuration. 

I should have some free time this weekend to get this change made, but wanted to get it documented.

**Comment by lmammino** [comment]
Feel free to submit a pull request if you can as I will have almost 0 free time until the next weekend so I can't look at this so soon...

**Comment by mtotheikle** [comment]
Will do. Just wanted to get issue entered incase this weekends work ends up taking longer than expected.

**Comment by lmammino** [comment]
@mtotheikle just updated. Seems to working for me, but I admit I have no time for accurate tests now... If it's good for you I'll close the issue :wink:

**Comment by mtotheikle** [comment]
This looks like it will work. I did a temp hack to make it work in my case and need to get the library back to original state before I can test this. Will check it out within a few days.

**Comment by lmammino** [comment]
Ok @mtotheikle! You can close the issue when you're sure it works :+1:

**Comment by lmammino** [comment]
Closing it...
