### ISSUE TITLE
Using option showName as false causes naming generation error

### ISSUE THREAD

**Issue by mtotheikle** [Oryzone/OryzoneMediaStorageBundle#30]
When using the oryzone_media_storage_media and setting the showName option to false, the SluggedNamingStrategy will fail since there is no name for the media.

Suggestions for fixes? Using hints on the model object works but I feel like that should not be needed.

**Comment by lmammino** [comment]
Sorry for the delay.
When you set `showName` option as `false` in the `oryzone_media_storage_media` it just hides the field but does not provide any logic to determinate a name for the media. You should implement your naming logic in your submit code before storing the media.

You just need to set the name of the media (`$media->setName('whatever you like');`) and it should be slugged (or processed by your custom naming strategy) automatically once the media is stored.
