### ISSUE TITLE
can't generate table from entity 

### ISSUE THREAD

**Issue by houssemeddinear** [Oryzone/OryzoneMediaStorageBundle#31]
hi , this my entity class
<?php

namespace Application\MainAppBundleBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Oryzone\Bundle\MediaStorageBundle\Entity\Media as BaseMedia;
/**
- Application\MainAppBundleBundle\Entity\Media
  *
- @ORM\Table(name="media")
- @ORM\Entity()
  */

class Media extends BaseMedia
{

```
/**
 * @ORM\Id
 * @ORM\Column(name="id", type="integer")
 * @ORM\GeneratedValue(strategy="AUTO")
 */

protected $id;

 /**
 * {@inheritDoc}
 */
public function getId()
{
    return $this->id;
}
```

}
?>

when i execute "php app/console doctrine:update:schema --force" i get this message 
nothing to update ... 
help please

**Comment by lmammino** [comment]
Really weird.
Do you have a full public repo to look at the complete code?

Can you check if the `media` table is present in your database?

**Comment by houssemeddinear** [comment]
yes of course , i checked my database , but i cant find media table 
i changed my orm mapping from auto to 
orm:
        entity_managers:
            default:
                connection:       default
                mappings:
                    ApplicationMainAppBundle: ~ 
                    # .... the rest of bundles
but i failed

**Comment by lmammino** [comment]
Really weird.
Can you try to add a new sample entity (unrelated to the media storage bundle) to see if it's a problem related to your app or to the bundle itself?

**Comment by houssemeddinear** [comment]
Resolved ✔ 
the problem: when I execute doctrine:schema:update, the update of the data base is based on the files in @ MyBundle / Resources / config / doctrine / MyFiles.orm.yml since I created my entity Entity / media.php and I have not Media.orm.yml the media table will not be created, so I deleted all files \* orm.yml and I execute php app / console doctrine.: schema: update and the table is created
Thank you.

**Comment by lmammino** [comment]
No prob. Happy you solved it!
